# Generated by Django 4.2.7 on 2025-04-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('candidate_answer', models.TextField(blank=True, null=True)),
                ('question_number', models.PositiveIntegerField()),
                ('content_score', models.FloatField(default=0.0)),
                ('voice_score', models.FloatField(default=0.0)),
                ('facial_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interview')),
            ],
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='job_posting',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewSession',
        ),
    ]
