# Generated by Django 4.2.7 on 2025-05-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interview',
            table='interviews_interview',
        ),
    ]
