# Generated by Django 4.2.7 on 2025-03-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
