# Generated by Django 4.2.7 on 2025-05-13 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import interview_applications.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv', models.FileField(upload_to=interview_applications.models.cv_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Interview Scheduled'), ('completed', 'Interview Completed'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('missing_skills', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.CharField(blank=True, max_length=20, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
