# Generated by Django 4.2.7 on 2025-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_application_match_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='requirements_matched',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills_matched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
