# Generated by Django 4.2.7 on 2025-04-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_applications.application'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
