# Generated by Django 4.2.7 on 2025-03-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_company_address_alter_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
    ]
