# Generated by Django 4.2.7 on 2025-04-29 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
