# Generated by Django 4.2.7 on 2025-05-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interview_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interview_id',
        ),
    ]
