# Generated by Django 4.2.7 on 2025-05-05 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interview_interview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
